import type { Student } from "@/types/student";
import { PHOTO_COLORS } from "./student-options";

// Temporary seed data — will be replaced by NestJS + Supabase backend later.
const SEED: Omit<Student, "photoColor">[] = [
  {
    slug: "maya-chen",
    name: "Maya Chen",
    university: "Stanford University",
    course: "Computer Science",
    year: "3rd",
    location: "Palo Alto, CA",
    openTo: ["internships"],
    availability: { from: "Jun 2026", to: "Sep 2026" },
    internshipLength: "3–6 mo",
    cvName: "maya-chen-cv.pdf",
    bio: "Building small tools for creators. Currently obsessed with on-device ML.",
    tags: ["React", "Figma", "PyTorch"],
    contactType: "linkedin",
    contact: "linkedin.com/in/mayachen",
    email: "maya@example.com",
    addedAt: "2026-05-14",
  },
  {
    slug: "diego-alvarez",
    name: "Diego Alvarez",
    university: "NYU Tisch",
    course: "Film & TV",
    year: "2nd",
    location: "Brooklyn, NY",
    openTo: ["freelance", "part-time"],
    availability: { from: "Now", to: "Ongoing" },
    internshipLength: null,
    cvName: "diego-alvarez-reel.pdf",
    bio: "Experimental docs and VR storytelling. Sundance shortlisted 2025.",
    tags: ["Premiere", "Cinematography", "AR"],
    contactType: "email",
    contact: "diego@hey.com",
    addedAt: "2026-05-13",
  },
  {
    slug: "priya-patel",
    name: "Priya Patel",
    university: "Imperial College London",
    course: "Mechanical Engineering",
    year: "4th",
    location: "London, UK",
    openTo: ["full-time", "internships"],
    availability: { from: "Sep 2026", to: "Ongoing" },
    internshipLength: "Summer only",
    cvName: "priya-patel-cv.pdf",
    bio: "Robots that play music. Recently soldered a marimba-playing arm.",
    tags: ["SolidWorks", "Arduino", "Python"],
    contactType: "portfolio",
    contact: "priya.engineer",
    addedAt: "2026-05-12",
  },
  {
    slug: "jordan-lee",
    name: "Jordan Lee",
    university: "RISD",
    course: "Industrial Design",
    year: "Masters",
    location: "Providence, RI",
    openTo: ["internships", "freelance"],
    availability: { from: "Jun 2026", to: "Aug 2026" },
    internshipLength: "Summer only",
    cvName: null,
    bio: "Soft goods, soft systems. Working on inflatable furniture for tiny apartments.",
    tags: ["Rhino", "Fabrication", "Sketch"],
    contactType: "linkedin",
    contact: "linkedin.com/in/jordanlee",
    addedAt: "2026-05-11",
  },
  {
    slug: "yuki-tanaka",
    name: "Yuki Tanaka",
    university: "UCLA",
    course: "Design Media Arts",
    year: "1st",
    location: "Los Angeles, CA",
    openTo: ["freelance"],
    availability: { from: "Now", to: "Ongoing" },
    internshipLength: null,
    cvName: "yuki-tanaka-portfolio.pdf",
    bio: "Generative type and motion. Big into TouchDesigner and risograph print.",
    tags: ["TouchDesigner", "Cinema 4D", "p5.js"],
    contactType: "portfolio",
    contact: "yuki.studio",
    addedAt: "2026-05-10",
  },
  {
    slug: "marcus-okafor",
    name: "Marcus Okafor",
    university: "Howard University",
    course: "Business + CS",
    year: "2nd",
    location: "Washington, DC",
    openTo: ["internships", "part-time"],
    availability: { from: "May 2026", to: "Aug 2026" },
    internshipLength: "1–3 mo",
    cvName: "marcus-okafor-cv.pdf",
    bio: "Fintech for emerging markets. Shipping a remittance MVP this summer.",
    tags: ["Python", "Strategy", "Figma"],
    contactType: "email",
    contact: "marcus@okafor.co",
    addedAt: "2026-05-09",
  },
  {
    slug: "ada-okeke",
    name: "Ada Okeke",
    university: "MIT",
    course: "EECS",
    year: "3rd",
    location: "Cambridge, MA",
    openTo: ["research", "internships"],
    availability: { from: "Sep 2026", to: "Jun 2027" },
    internshipLength: "6+ mo",
    cvName: "ada-okeke-cv.pdf",
    bio: "Low-power edge ML. Made a sparrow recognizer that runs on a coin cell.",
    tags: ["C++", "PyTorch", "Embedded"],
    contactType: "linkedin",
    contact: "linkedin.com/in/adaokeke",
    addedAt: "2026-05-08",
  },
  {
    slug: "sofia-rinaldi",
    name: "Sofia Rinaldi",
    university: "Politecnico di Milano",
    course: "Architecture",
    year: "PhD",
    location: "Milan, Italy",
    openTo: ["research", "full-time"],
    availability: { from: "Jan 2027", to: "Ongoing" },
    internshipLength: null,
    cvName: "sofia-rinaldi-cv.pdf",
    bio: "Computational urban design. Mapping climate microhabitats in Italian piazzas.",
    tags: ["Grasshopper", "Rhino", "GIS"],
    contactType: "portfolio",
    contact: "sofia.studio",
    addedAt: "2026-05-07",
  },
];

export const SEED_STUDENTS: Student[] = SEED.map((s, i) => ({
  ...s,
  photoColor: PHOTO_COLORS[i % PHOTO_COLORS.length],
}));
